---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Install nginx
  yum:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "RedHat"

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Copy index.html file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart nginx
  when: ansible_os_family == "Debian"

- name: Copy index.html file
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  become: yes
  notify: restart nginx
  when: ansible_os_family == "RedHat"
